nameList: /scratch/gent/vo/000/gvo00027/vsc42927/refList.csv
sampleFolder: /data/gent/vo/000/gvo00027/vsc42927/bismarkPipeline/methylation_extractor_output/references/
DMRfolder: /scratch/gent/vo/000/gvo00027/vsc42927/DMRfinder
scriptFolder: /data/gent/vo/000/gvo00027/vsc42927/scripts/DMRfinder/
